### ISSUE TITLE
Can't solve phantom button presses and controller disconnecting!

### ISSUE THREAD

**Issue by DarthMotzkus** [L10N37/Atmega-N64-IGR-#2]
Hi. How are you?
Done as you said on the project, here is my installation diagram and Arduino board pics below.
Can you help me to solve the phantom button presses and controller disconnection problems?

![image](https://github.com/user-attachments/assets/d66fc2b7-2d0e-4a13-9f22-50320e4364a6)

![12](https://github.com/user-attachments/assets/4aed3b50-6f8e-48ef-a51c-e0d9328be444)

![13](https://github.com/user-attachments/assets/f17065c3-d082-43ca-91c0-5571a2b5a066)

Compiled with the files you provided. Done the mod, using a 120R (Ohms) 1/4W 1% resistor on the serial pin on PIF. The Combo don't have the R and it needs to hold for 1 second. The combo works, but many issues appears.
My MB is a CPU04. Using a Nano Arduino with atMega 328p.

-----------------------------------------------------------------------------------------------------------------------------------------------------
ISSUES:

- Some games, like F-ZERO X, phantom disconnect the controller, and don't receive the inputs anymore until it resets the console (the combo L+A+B+Z works). But other games this do not happens.

- When i left the console on everdrive list for example, without pressing any button, it phantom press Z or start or R randomly.

- Using a controller test utility rom, i can see the controller disconnect and connect again for 100ms, it's super quick, In every 10 seconds.

- Other issue, rumble pak inserted (with AAA batteries, no mods) on controller, with constant rumble testing, it disconnect entirely the controller after 3/4 seconds on the controller test utility as well, the program even quit the controller screen (it differs of the 100ms disconnection i mentioned).
-----------------------------------------------------------------------------------------------------------------------------------------------------

Without the board installed, all of the issues above do not happen. 
Tried to swap 5V point on arduino to vcc/vin. Nothing changed. 
Left without resistor on D2, nothing changed. 
Disconnected the 5V wire and ground, the Arduino keeps working (i think because of serial voltage in PIF pinout 16).

Any help will be much appreciate. More friends of mine are hoping we can solve this to do the same mod.
Thanks in advance.

**Comment by L10N37** [comment]
Unfortunately this was a quick hack up left here for someone else to solve and take on as their own project.

I used an ED64 and played through heaps of games, Including clocking lylat wars (or what ever it's called when it's the US version, Starfox 64?) and the only issue on any game was start button sometimes getting phantom pressed. I believe it needs a buffer to rectify, and I don't think the resistor helps. 

Any other issues I didn't personally encounter.
